"""Narrative helpers: format derived stats for the LLM and a templated fallback.

Only aggregated statistics from the profile dict are used here — never raw rows
(PII rule). The templated fallback produces a usable narrative when the Gemini
call fails, so the run always completes.
"""
from __future__ import annotations

from typing import Any


def build_stats_summary(profile: dict[str, Any]) -> str:
    """Render the derived stats as compact text for the Gemini user prompt.

    Contains ONLY aggregated statistics — no raw rows.
    """
    shape = profile.get("shape", {})
    n_rows = shape.get("rows", 0)
    n_cols = shape.get("columns", 0)
    numeric = profile.get("numeric_columns", [])
    categorical = profile.get("categorical_columns", [])

    lines = [
        f"Dataset shape: {n_rows} rows x {n_cols} columns.",
        f"Numeric columns ({len(numeric)}): {', '.join(numeric) or 'none'}.",
        f"Categorical columns ({len(categorical)}): {', '.join(categorical) or 'none'}.",
        "",
        "Missingness (columns with missing values):",
    ]
    missing = [m for m in profile.get("missingness", []) if m.get("missing", 0) > 0]
    if missing:
        for m in missing:
            lines.append(f"  - {m['name']}: {m['missing']} missing ({m['missing_pct']}%)")
    else:
        lines.append("  - none (no missing values in any column)")

    lines.append("")
    lines.append("Numeric column summaries:")
    numeric_summarized = False
    for col in profile.get("columns", []):
        if col.get("kind") != "numeric" or col.get("mean") is None:
            continue
        numeric_summarized = True
        lines.append(
            f"  - {col['name']}: min={col['min']}, mean={col['mean']}, "
            f"max={col['max']}, std={col['std']}, "
            f"quartiles=[{col['q25']}, {col['q50']}, {col['q75']}]"
        )
    if not numeric_summarized:
        lines.append("  - none")

    lines.append("")
    lines.append("Top categorical values:")
    cat_summarized = False
    for col in profile.get("columns", []):
        if col.get("kind") != "categorical":
            continue
        cat_summarized = True
        top = col.get("top")
        lines.append(
            f"  - {col['name']}: {col.get('unique')} unique values"
            + (f", most common '{top}' ({col.get('top_freq')} rows)" if top else "")
        )
    if not cat_summarized:
        lines.append("  - none")

    correlations = profile.get("correlations", [])
    if correlations:
        lines.append("")
        lines.append("Strongest correlations:")
        for c in correlations:
            lines.append(f"  - {c['a']} vs {c['b']}: r={c['r']}")

    return "\n".join(lines)


def templated_narrative(profile: dict[str, Any]) -> str:
    """Deterministic fallback narrative built from derived stats only."""
    shape = profile.get("shape", {})
    n_rows = shape.get("rows", 0)
    n_cols = shape.get("columns", 0)
    numeric = profile.get("numeric_columns", [])
    categorical = profile.get("categorical_columns", [])

    parts = [
        f"This dataset contains {n_rows} rows and {n_cols} columns "
        f"({len(numeric)} numeric, {len(categorical)} categorical)."
    ]

    missing = sorted(
        (m for m in profile.get("missingness", []) if m.get("missing", 0) > 0),
        key=lambda m: m.get("missing_pct", 0),
        reverse=True,
    )
    if missing:
        worst = missing[0]
        parts.append(
            f"{len(missing)} column(s) have missing values; the most affected is "
            f"'{worst['name']}' at {worst['missing_pct']}% missing."
        )
    else:
        parts.append("No missing values were detected in any column.")

    correlations = profile.get("correlations", [])
    if correlations:
        top = correlations[0]
        parts.append(
            f"The strongest correlation is between '{top['a']}' and '{top['b']}' "
            f"(r={top['r']})."
        )
    elif numeric:
        parts.append(
            "Review the numeric summary statistics and charts below for distributions and outliers."
        )
    else:
        parts.append("No numeric columns are available, so charts requiring numerics were omitted.")

    parts.append("(This summary was generated by the built-in template; the AI narrative was unavailable.)")
    return " ".join(parts)
